// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb3yhhvev8T3KLVLsSkQUq6wGcNXRBdwc',
    appId: '1:221934147274:web:adc3acecd3582d111c4633',
    messagingSenderId: '221934147274',
    projectId: 'hack-bebuicii',
    authDomain: 'hack-bebuicii.firebaseapp.com',
    storageBucket: 'hack-bebuicii.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfEcMgCqTs3ll4bjtYHK-id_hSIZhtL2s',
    appId: '1:221934147274:android:c97d97162ef468691c4633',
    messagingSenderId: '221934147274',
    projectId: 'hack-bebuicii',
    storageBucket: 'hack-bebuicii.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnDNv1C_MbfqP72_Zbv3IV07r8zhtFZw4',
    appId: '1:221934147274:ios:1cf400ccf9297a761c4633',
    messagingSenderId: '221934147274',
    projectId: 'hack-bebuicii',
    storageBucket: 'hack-bebuicii.appspot.com',
    iosClientId: '221934147274-oegjjeq7urbr2o7sbsaqhqq31s4cnje1.apps.googleusercontent.com',
    iosBundleId: 'com.example.bankingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnDNv1C_MbfqP72_Zbv3IV07r8zhtFZw4',
    appId: '1:221934147274:ios:1cf400ccf9297a761c4633',
    messagingSenderId: '221934147274',
    projectId: 'hack-bebuicii',
    storageBucket: 'hack-bebuicii.appspot.com',
    iosClientId: '221934147274-oegjjeq7urbr2o7sbsaqhqq31s4cnje1.apps.googleusercontent.com',
    iosBundleId: 'com.example.bankingApp',
  );
}
